CLASS zbp_r_online_shop_c2825 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF
zr_online_shop_c2825.
PUBLIC SECTION.
class-DATA cv_pr_mapped TYPE RESPONSE FOR MAPPED i_purchaserequisitiontp.
ENDCLASS.

CLASS zbp_r_online_shop_c2825 IMPLEMENTATION.
ENDCLASS.
